version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - type:automation

  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: monthly
    labels:
      - type:automation
